services:
  # Neo4j Graph Database
  neo4j:
    image: neo4j:5.11-community
    container_name: lca-neo4j
    environment:
      - NEO4J_AUTH=neo4j/metallurgy123
      - NEO4J_PLUGINS=["graph-data-science"]
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1g
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - lca-network

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: lca-backend
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=metallurgy123
      - DATABASE_URL=sqlite:///./lca_data.db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./ml-models:/app/ml-models
    depends_on:
      - neo4j
    networks:
      - lca-network

  # Svelte Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: lca-frontend
    ports:
      - "5000:5000"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - lca-network

  # Caddy Reverse Proxy
  caddy:
    image: caddy:2.7-alpine
    container_name: lca-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - lca-network

volumes:
  neo4j_data:
  neo4j_logs:
  caddy_data:
  caddy_config:

networks:
  lca-network:
    driver: bridge